<<<<<<< HEAD
name ci
=======
name: ci
>>>>>>> origin/main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Check out code 
        uses: actions/checkout@v4
      
=======
      - name: Check out code
        uses: actions/checkout@v4

>>>>>>> origin/main
      - name: Check out go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
<<<<<<< HEAD
        
      - name: Force failures
        run: exit 1
=======

      - name: Run tests
        run: go test ./...

      - name: Check go version
        run: go version
>>>>>>> origin/main
