name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check out go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: Force failures
        run: go version
